apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  type: NodePort
  ports:
    - name: vote-service
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: vote